version: "3.3"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./docker:/docker-entrypoint-initdb.d/
      - data-mongodb:/data/db
    #restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod
    networks:
      - jeux

volumes:
  data-mongodb: {}

networks:
  jeux:
